---
- name: Add PostgreSQL repository
  copy:
    src: postgresql.list
    dest: /etc/apt/sources.list.d/postgresql.list
- name: Add PostgreSQL key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
- name: Update apt packages
  apt:
    # upgrade: yes
    update_cache: yes
- name: Install PostgreSQL 12
  apt:
    name:
      - postgresql-12
      - postgresql-client-12
    state: present
- name: Copy config file postgresql.conf
  copy:
    src: postgresql.conf
    dest: /etc/postgresql/12/main/postgresql.conf
- name: Copy config file pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/12/main/pg_hba.conf
- name: reload systemd
  systemd:
    daemon_reload: yes
- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted
    enabled: yes
# - name: Create database freeswitch PostgreSQL
#   become: yes
#   become_user: postgres
#   become_method: sudo
#   community.postgresql.postgresql_db:
#     name: "{{ freeswitch_db_name }}"
# - name: Create user freeswitch
#   become: yes
#   become_user: postgres
#   become_method: sudo
#   community.postgresql.postgresql_user:
#     db: "{{ freeswitch_db_name }}"
#     name: "{{ freeswitch_db_user }}"
#     password: "{{ fs_db_pass }}"
#     priv: ALL
#     role_attr_flags: SUPERUSER
